package com.timachado.brothermatrizes.font

import com.timachado.brothermatrizes.core.embroidery.EmbroideryBounds
import com.timachado.brothermatrizes.core.embroidery.EmbroideryDesign
import com.timachado.brothermatrizes.core.embroidery.EmbroideryPoint
import com.timachado.brothermatrizes.core.embroidery.EmbroideryStressPolicy
import com.timachado.brothermatrizes.core.embroidery.HoopValidator
import com.timachado.brothermatrizes.core.embroidery.MatrixConverter
import com.timachado.brothermatrizes.core.embroidery.SatinUnderlayMode
import com.timachado.brothermatrizes.core.embroidery.StitchCommand
import com.timachado.brothermatrizes.core.embroidery.TextMatrixOptions
import java.util.Locale
import kotlin.math.abs
import kotlin.math.ceil
import kotlin.math.floor
import kotlin.math.hypot
import kotlin.math.max
import kotlin.math.roundToInt

/**
 * Reimplementation independently designed from normal embroidery geometry.
 *
 * It does NOT use MaoDesign binaries or proprietary routines. The reference
 * APK is a proprietary .NET MAUI application and contains no recorded
 * stitch-out for the user's font/name. Exact equivalence requires comparing
 * matching machine files generated by that app.
 *
 * Distinct pipeline: actual font outline -> filled binary mask -> medial axis
 * -> edge-disjoint stroke paths -> transverse satin rails -> one center-run
 * underlay (optional) -> one satin coverage -> next path / next glyph.
 *
 * There is deliberately no Maria-specific image heuristic, global scanline
 * column ordering, multi-pass per-column locking or cleanup of sub-0.4mm
 * stitches. The rendered preview and export share the same command sequence.
 */
internal object CleanRoomSatinEngine {
    internal data class V(val x: Float, val y: Float)
    internal data class Rail(val a: V, val b: V) {
        val middle: V get() = V((a.x + b.x) / 2f, (a.y + b.y) / 2f)
    }
    internal data class PlannedGlyph(
        val rails: List<List<Rail>>,
        val sampledEdges: Int,
        val duplicateRailsDiscarded: Int
    )

    private data class Cell(val x: Int, val y: Int)
    private data class Edge(val a: Int, val b: Int) {
        companion object {
            fun of(a: Int, b: Int) =
                if (a <= b) Edge(a, b) else Edge(b, a)
        }
    }
    private data class Raster(
        val width: Int, val height: Int, val step: Float,
        val left: Float, val top: Float, val mask: BooleanArray
    ) {
        fun index(x: Int, y: Int) = y * width + x
        fun inside(x: Int, y: Int) =
            x in 0 until width && y in 0 until height && mask[index(x, y)]
        fun point(index: Int): V {
            val x = index % width
            val y = index / width
            return V(left + x * step, top + y * step)
        }
    }

    fun generate(
        font: ImportedFont,
        sourceText: String,
        options: TextMatrixOptions,
        filePrefix: String
    ): Result<EmbroideryDesign> = runCatching {
        val text = sourceText.trim().take(24)
        require(text.isNotBlank()) { "Digite um nome." }
        require(options.heightMm in 4f..60f) { "Altura fora de 4 a 60 mm." }
        require(options.satinDensityMm in 0.3f..1.2f) {
            "A densidade Satin deve ficar entre 0,3 e 1,2 mm."
        }
        require(options.satinPullCompensationMm in 0f..1f) {
            "Compensação de repuxo fora do intervalo."
        }
        val format = options.outputFormat.uppercase(Locale.ROOT)
        require(format in MatrixConverter.supportedFormats) {
            "Formato de matriz não suportado."
        }
        val heightUnits = options.heightMm * 10f
        val spacing = heightUnits * 0.04f + options.spacingMm * 10f
        val outlines = AndroidSkiaOutlineExtractor.extract(
            font = font,
            text = text,
            targetCapHeightUnits = heightUnits,
            spacingUnits = spacing,
            rotationDegrees = options.rotationDegrees
        )
        val points = mutableListOf<EmbroideryPoint>()
        val stitcher = Stitcher(points)
        var sewnGlyphs = 0
        outlines.glyphPolygons.forEachIndexed { glyphIndex, glyph ->
            val contours = glyph.map { contour -> contour.map { V(it.x, it.y) } }
            if (contours.isEmpty()) return@forEachIndexed
            val plan = planContours(
                contours,
                densityMm = options.satinDensityMm,
                pullMm = options.satinPullCompensationMm
            )
            require(plan.rails.isNotEmpty()) {
                "A fonte não produziu uma faixa Satin segura na letra " +
                    (glyphIndex + 1) + ". Ajuste a altura ou a fonte."
            }
            stitcher.sewGlyph(plan.rails, options.satinUnderlayMode)
            sewnGlyphs++
        }
        require(sewnGlyphs > 0 && points.any { it.command == StitchCommand.STITCH }) {
            "Não foram geradas pontadas válidas."
        }
        val last = points.last()
        points.add(last.copy(command = StitchCommand.END))
        val coords = points.filter { it.command != StitchCommand.END }
        val bounds = EmbroideryBounds(
            minXUnits = coords.minOf { it.xUnits },
            maxXUnits = coords.maxOf { it.xUnits },
            minYUnits = coords.minOf { it.yUnits },
            maxYUnits = coords.maxOf { it.yUnits }
        )
        val design = EmbroideryDesign(
            fileName = "$filePrefix-" +
                text.lowercase(Locale.ROOT).replace(Regex("[^a-z0-9_-]"), "-") +
                "." + format.lowercase(Locale.ROOT),
            format = format,
            label = text,
            points = points,
            bounds = bounds,
            stitchCount = points.count { it.command == StitchCommand.STITCH },
            jumpCount = points.count { it.command == StitchCommand.JUMP },
            colorChanges = 0,
            endFound = true,
            sourceBytes = ByteArray(0),
            threadColors = listOf(options.color),
            sourceYAxisDown = true,
            isModified = true,
            hoopProfile = options.hoopProfile,
            fabricProfile = options.fabricProfile
        )
        EmbroideryStressPolicy.requireGeneratedSafe(design)
        if (options.enforceHoop && options.hoopProfile != null) {
            require(HoopValidator.validate(design, options.hoopProfile).fits) {
                "O bordado ultrapassa o bastidor selecionado."
            }
        }
        design
    }

    internal fun planContours(
        contours: List<List<V>>,
        densityMm: Float,
        pullMm: Float = 0.2f
    ): PlannedGlyph {
        require(densityMm in 0.3f..1.2f)
        val raster = rasterize(contours, densityMm)
        val skeleton = thin(raster)
        val skeletonPixels = skeleton.count { it }
        if (skeletonPixels < 1) return PlannedGlyph(emptyList(), 0, 0)
        val routes = traceEdges(raster, skeleton)
        val pitch = densityMm * 10f
        val claimed = HashMap<Pair<Int, Int>, MutableList<Rail>>()
        val tolerance = (pitch * 0.28f).coerceIn(0.65f, 1.4f)
        fun cell(v: V) =
            floor(v.x / (tolerance * 2.4f)).toInt() to
                floor(v.y / (tolerance * 2.4f)).toInt()
        fun sameRail(a: Rail, b: Rail): Boolean =
            length(a.middle, b.middle) <= tolerance &&
                (
                    (length(a.a, b.a) <= tolerance && length(a.b, b.b) <= tolerance) ||
                    (length(a.a, b.b) <= tolerance && length(a.b, b.a) <= tolerance)
                )
        fun seen(rail: Rail): Boolean {
            val (cx, cy) = cell(rail.middle)
            for (dx in -1..1) for (dy in -1..1) {
                if (claimed[cx + dx to cy + dy].orEmpty().any { sameRail(it, rail) }) {
                    return true
                }
            }
            claimed.getOrPut(cell(rail.middle)) { mutableListOf() }.add(rail)
            return false
        }
        val result = mutableListOf<List<Rail>>()
        var duplicates = 0
        var previous: V? = null
        val remaining = routes.map { it.toMutableList() }.toMutableList()
        while (remaining.isNotEmpty()) {
            val start = previous
            val routeIndex = if (start == null) {
                remaining.indices.minByOrNull { i ->
                    // Begin at the lower/leftmost physical beginning of the first glyph.
                    val p = remaining[i].first()
                    p.x * 0.6f - p.y * 0.4f
                } ?: 0
            } else {
                remaining.indices.minByOrNull { i ->
                    minOf(
                        length(start, remaining[i].first()),
                        length(start, remaining[i].last())
                    )
                } ?: 0
            }
            val route = remaining.removeAt(routeIndex)
            if (start != null &&
                length(start, route.last()) < length(start, route.first())) {
                route.reverse()
            }
            val interpolated = resample(route, pitch)
            var batch = mutableListOf<Rail>()
            fun endBatch() {
                if (batch.isNotEmpty()) result += batch
                batch = mutableListOf()
            }
            interpolated.forEachIndexed { i, c ->
                val prev = interpolated[(i - 1).coerceAtLeast(0)]
                val next = interpolated[(i + 1).coerceAtMost(interpolated.lastIndex)]
                val tangent = normalized(V(next.x - prev.x, next.y - prev.y))
                if (tangent == null) return@forEachIndexed
                val row = crossSection(raster, c, V(-tangent.y, tangent.x), pullMm * 10f)
                if (row == null || length(row.a, row.b) < 4f) {
                    endBatch()
                } else if (seen(row)) {
                    duplicates++
                    endBatch()
                } else {
                    batch.add(row)
                }
            }
            endBatch()
            previous = route.lastOrNull()
        }
        return PlannedGlyph(result, routes.sumOf { it.size }, duplicates)
    }

    private fun rasterize(contours: List<List<V>>, densityMm: Float): Raster {
        val points = contours.flatten()
        require(points.isNotEmpty()) { "Fonte sem contorno." }
        val minX = points.minOf { it.x }
        val maxX = points.maxOf { it.x }
        val minY = points.minOf { it.y }
        val maxY = points.maxOf { it.y }
        var step = max(1.5f, densityMm * 10f * 0.55f)
        var width = ceil((maxX - minX) / step).toInt() + 5
        var height = ceil((maxY - minY) / step).toInt() + 5
        while (width.toLong() * height.toLong() > 350_000) {
            step *= 1.2f
            width = ceil((maxX - minX) / step).toInt() + 5
            height = ceil((maxY - minY) / step).toInt() + 5
        }
        val left = minX - step * 2
        val top = minY - step * 2
        val mask = BooleanArray(width * height)
        for (y in 1 until height - 1) {
            val rowY = top + y * step
            val intersections = mutableListOf<Float>()
            contours.forEach { polygon ->
                if (polygon.size < 3) return@forEach
                polygon.indices.forEach { i ->
                    val a = polygon[i]
                    val b = polygon[(i + 1) % polygon.size]
                    if ((a.y <= rowY && b.y > rowY) ||
                        (b.y <= rowY && a.y > rowY)) {
                        intersections += a.x +
                            (rowY - a.y) * (b.x - a.x) / (b.y - a.y)
                    }
                }
            }
            intersections.sort()
            for (i in 0 until intersections.size - 1 step 2) {
                val from = max(1, ceil((intersections[i] - left) / step).toInt())
                val to = minOf(width - 2,
                    floor((intersections[i + 1] - left) / step).toInt())
                for (x in from..to) mask[y * width + x] = true
            }
        }
        return Raster(width, height, step, left, top, mask)
    }

    // Zhang-Suen skeletonization: a mask pixel may be deleted only if the
    // local 8-neighborhood remains connected. Boundary crossings are unique.
    private fun thin(raster: Raster): BooleanArray {
        val pixels = raster.mask.copyOf()
        val w = raster.width
        val h = raster.height
        fun on(x: Int, y: Int) = pixels[y * w + x]
        var changed = true
        var pass = 0
        while (changed && pass < 220) {
            changed = false
            for (phase in 0..1) {
                val erase = mutableListOf<Int>()
                for (y in 1 until h - 1) for (x in 1 until w - 1) {
                    if (!on(x, y)) continue
                    val n = booleanArrayOf(
                        on(x, y-1), on(x+1, y-1), on(x+1, y),
                        on(x+1, y+1), on(x, y+1), on(x-1, y+1),
                        on(x-1, y), on(x-1, y-1)
                    )
                    val count = n.count { it }
                    if (count !in 2..6) continue
                    val transitions = n.indices.count { !n[it] && n[(it+1)%8] }
                    if (transitions != 1) continue
                    val p2 = n[0]; val p4 = n[2]; val p6 = n[4]; val p8 = n[6]
                    val condition = if (phase == 0) {
                        !(p2 && p4 && p6) && !(p4 && p6 && p8)
                    } else {
                        !(p2 && p4 && p8) && !(p2 && p6 && p8)
                    }
                    if (condition) erase += y * w + x
                }
                erase.forEach { pixels[it] = false }
                if (erase.isNotEmpty()) changed = true
            }
            pass++
        }
        return pixels
    }

    private fun traceEdges(raster: Raster, skeleton: BooleanArray): List<List<V>> {
        val w = raster.width
        val h = raster.height
        fun neighbors(i: Int): List<Int> {
            val x = i % w; val y = i / w
            val out = mutableListOf<Int>()
            for (dy in -1..1) for (dx in -1..1) {
                if (dx == 0 && dy == 0) continue
                val nx = x + dx; val ny = y + dy
                if (nx !in 0 until w || ny !in 0 until h) continue
                val neighbor = ny * w + nx
                if (!skeleton[neighbor]) continue
                // 4-connected orthogonal alternatives remove diagonal
                // shortcuts that generate loops at 90-degree bends.
                if (dx != 0 && dy != 0 &&
                    (skeleton[y * w + nx] || skeleton[ny * w + x])) continue
                out += neighbor
            }
            return out
        }
        val nodes = skeleton.indices.filter { skeleton[it] }
        val used = HashSet<Edge>()
        val paths = mutableListOf<List<V>>()
        fun walk(source: Int, first: Int) {
            var previous = source
            var current = first
            val track = mutableListOf(source, first)
            used.add(Edge.of(source, first))
            while (true) {
                val available = neighbors(current)
                    .filter { it != previous && Edge.of(it, current) !in used }
                if (available.size != 1) break
                val next = available[0]
                used.add(Edge.of(current, next))
                previous = current
                current = next
                track.add(current)
                if (current == source) break
            }
            if (track.size >= 3) paths += track.map(raster::point)
        }
        // Endpoints / branches first; loops and remaining edges second.
        val ordered = nodes.sortedWith(compareBy<Int> {
            if (neighbors(it).size == 2) 1 else 0
        }.thenBy { it % w })
        ordered.forEach { node ->
            neighbors(node).forEach { next ->
                if (Edge.of(node, next) !in used) walk(node, next)
            }
        }
        return paths
    }

    private fun resample(path: List<V>, pitch: Float): List<V> {
        if (path.size < 2) return path
        val lengths = path.zipWithNext().map { (a,b) -> length(a,b) }
        val total = lengths.sum()
        if (total < pitch * 0.55f) return path
        val count = max(2, (total / pitch).roundToInt() + 1)
        val samples = mutableListOf<V>()
        var seg = 0
        var before = 0f
        for (i in 0 until count) {
            val d = total * i / (count - 1)
            while (seg < lengths.lastIndex && before + lengths[seg] < d) {
                before += lengths[seg]
                seg++
            }
            val fraction = if (lengths[seg] <= 0f) 0f else
                ((d - before) / lengths[seg]).coerceIn(0f,1f)
            val a = path[seg]
            val b = path[seg+1]
            samples += V(
                a.x + (b.x - a.x) * fraction,
                a.y + (b.y - a.y) * fraction
            )
        }
        return samples
    }

    private fun crossSection(
        mask: Raster, center: V, normal: V, pullUnits: Float
    ): Rail? {
        val sampling = minOf(0.85f, mask.step / 2f)
        fun insideAt(x: Float, y: Float): Boolean {
            val xi = ((x - mask.left) / mask.step).roundToInt()
            val yi = ((y - mask.top) / mask.step).roundToInt()
            return mask.inside(xi, yi)
        }
        if (!insideAt(center.x, center.y)) return null
        val maxExtent = 35f // 7 mm full satin width limit
        fun edge(sign: Float): Float {
            var d = 0f
            while (d <= maxExtent &&
                insideAt(
                    center.x + normal.x * d * sign,
                    center.y + normal.y * d * sign
                )) d += sampling
            return (d - sampling).coerceAtLeast(0f)
        }
        val a = edge(-1f)
        val b = edge(1f)
        if (a + b < 3f) return null
        return Rail(
            V(center.x - normal.x * (a + pullUnits),
                center.y - normal.y * (a + pullUnits)),
            V(center.x + normal.x * (b + pullUnits),
                center.y + normal.y * (b + pullUnits))
        )
    }

    internal fun stitchPlannedGlyphForTest(
        planned: PlannedGlyph,
        underlay: SatinUnderlayMode = SatinUnderlayMode.NONE
    ): List<EmbroideryPoint> {
        val points = mutableListOf<EmbroideryPoint>()
        Stitcher(points).sewGlyph(planned.rails, underlay)
        return points
    }

    private class Stitcher(val points: MutableList<EmbroideryPoint>) {
        private var needle: V? = null
        private fun command(p: V, cmd: StitchCommand) {
            val x = p.x.roundToInt()
            val y = p.y.roundToInt()
            val last = points.lastOrNull()
            if (last != null &&
                last.xUnits == x && last.yUnits == y &&
                last.command == cmd) return
            require(points.size < EmbroideryStressPolicy.MAX_GENERATED_COMMANDS) {
                "A fonte gerou pontos demais; tente menor altura ou outro estilo."
            }
            points += EmbroideryPoint(x, y, cmd, 0)
            needle = p
        }
        private fun jump(p: V) {
            val start = needle
            if (start != null && length(start, p) < 0.5f) return
            command(p, StitchCommand.JUMP)
        }
        private fun sew(p: V) {
            val start = needle
            if (start == null) { jump(p); return }
            val distance = length(start, p)
            if (distance < 0.45f) return
            val chunks = max(1, ceil(distance / 70f).toInt())
            for (k in 1..chunks) {
                val t = k.toFloat() / chunks
                command(V(start.x+(p.x-start.x)*t, start.y+(p.y-start.y)*t),
                    StitchCommand.STITCH)
            }
        }
        fun sewGlyph(paths: List<List<Rail>>, underlay: SatinUnderlayMode) {
            var anchored = false
            var previous: V? = needle
            paths.forEach { original ->
                if (original.isEmpty()) return@forEach
                val first = original.first().middle
                val last = original.last().middle
                val rows = if (previous != null &&
                    length(previous!!, last) < length(previous!!, first)) {
                    original.asReversed()
                } else original
                val begin = rows.first().middle
                val doUnderlay = underlay != SatinUnderlayMode.NONE && rows.size >= 6
                if (doUnderlay) {
                    jump(begin)
                    // One center run, then satin in reverse without
                    // retracing the center back to the start.
                    for (index in rows.indices step 5) sew(rows[index].middle)
                    sew(rows.last().middle)
                }
                val cover = if (doUnderlay) rows.asReversed() else rows
                val entry = cover.first().a
                val lastPos = needle
                if (lastPos == null || length(lastPos, entry) > 16f) jump(entry)
                else sew(entry)
                if (!anchored) {
                    // One short tie-in for this glyph, not every medial branch.
                    val r = cover.first()
                    val t = V(r.a.x + (r.b.x-r.a.x)*0.08f,
                        r.a.y + (r.b.y-r.a.y)*0.08f)
                    sew(t)
                    sew(r.a)
                    anchored = true
                }
                cover.forEach { rail ->
                    sew(rail.a)
                    sew(rail.b)
                }
                previous = needle
            }
            // There are deliberately NO per-path tie-off round trips.
            // The machine-facing finishing policy handles last tie/trim.
        }
    }

    private fun length(a: V, b: V) =
        hypot((b.x-a.x).toDouble(), (b.y-a.y).toDouble()).toFloat()
    private fun normalized(v: V): V? {
        val n = hypot(v.x.toDouble(), v.y.toDouble()).toFloat()
        return if (n < 0.0001f) null else V(v.x/n, v.y/n)
    }
}
