package com.timachado.brothermatrizes.font

import com.timachado.brothermatrizes.core.embroidery.EmbroideryBounds
import com.timachado.brothermatrizes.core.embroidery.EmbroideryDesign
import com.timachado.brothermatrizes.core.embroidery.EmbroideryPoint
import com.timachado.brothermatrizes.core.embroidery.EmbroideryStressPolicy
import com.timachado.brothermatrizes.core.embroidery.HoopValidator
import com.timachado.brothermatrizes.core.embroidery.MatrixConverter
import com.timachado.brothermatrizes.core.embroidery.SatinUnderlayMode
import com.timachado.brothermatrizes.core.embroidery.StitchCommand
import com.timachado.brothermatrizes.core.embroidery.TextMatrixOptions
import java.util.Locale
import kotlin.math.abs
import kotlin.math.ceil
import kotlin.math.floor
import kotlin.math.hypot
import kotlin.math.max
import kotlin.math.roundToInt

/**
 * Reimplementation independently designed from normal embroidery geometry.
 *
 * It does NOT use MaoDesign binaries or proprietary routines. The reference
 * APK is a proprietary .NET MAUI application and contains no recorded
 * stitch-out for the user's font/name. Exact equivalence requires comparing
 * matching machine files generated by that app.
 *
 * Distinct pipeline: actual font outline -> filled binary mask -> medial axis
 * -> edge-disjoint stroke paths -> transverse satin rails -> one center-run
 * underlay (optional) -> one satin coverage -> next path / next glyph.
 *
 * There is deliberately no Maria-specific image heuristic, global scanline
 * column ordering, multi-pass per-column locking or cleanup of sub-0.4mm
 * stitches. The rendered preview and export share the same command sequence.
 */
internal object CleanRoomSatinEngine {
    internal data class V(val x: Float, val y: Float)
    internal data class Rail(val a: V, val b: V) {
        val middle: V get() = V((a.x + b.x) / 2f, (a.y + b.y) / 2f)
    }
    internal data class PlannedGlyph(
        val rails: List<List<Rail>>,
        val sampledEdges: Int,
        val duplicateRailsDiscarded: Int
    )

    private data class Cell(val x: Int, val y: Int)
    private data class Edge(val a: Int, val b: Int) {
        companion object {
            fun of(a: Int, b: Int) =
                if (a <= b) Edge(a, b) else Edge(b, a)
        }
    }
    private data class Raster(
        val width: Int, val height: Int, val step: Float,
        val left: Float, val top: Float, val mask: BooleanArray
    ) {
        fun index(x: Int, y: Int) = y * width + x
        fun inside(x: Int, y: Int) =
            x in 0 until width && y in 0 until height && mask[index(x, y)]
        fun point(index: Int): V {
            val x = index % width
            val y = index / width
            return V(left + x * step, top + y * step)
        }
    }

    fun generate(
        font: ImportedFont,
        sourceText: String,
        options: TextMatrixOptions,
        filePrefix: String
    ): Result<EmbroideryDesign> = runCatching {
        val text = sourceText.trim().take(24)
        require(text.isNotBlank()) { "Digite um nome." }
        require(options.heightMm in 4f..60f) { "Altura fora de 4 a 60 mm." }
        require(options.satinDensityMm in 0.3f..1.2f) {
            "A densidade Satin deve ficar entre 0,3 e 1,2 mm."
        }
        require(options.satinPullCompensationMm in 0f..1f) {
            "Compensação de repuxo fora do intervalo."
        }
        val format = options.outputFormat.uppercase(Locale.ROOT)
        require(format in MatrixConverter.supportedFormats) {
            "Formato de matriz não suportado."
        }
        val heightUnits = options.heightMm * 10f
        // Não inserir espaçamento automático: fontes cursivas dependem
        // de encaixe e kerning para manter suas ligações entre letras.
        val spacing = options.spacingMm * 10f
        val outlines = AndroidSkiaOutlineExtractor.extract(
            font = font,
            text = text,
            targetCapHeightUnits = heightUnits,
            spacingUnits = spacing,
            rotationDegrees = options.rotationDegrees
        )
        val points = mutableListOf<EmbroideryPoint>()
        val stitcher = Stitcher(points)
        var sewnGlyphs = 0
        outlines.glyphPolygons.forEachIndexed { glyphIndex, glyph ->
            val contours = glyph.map { contour -> contour.map { V(it.x, it.y) } }
            if (contours.isEmpty()) return@forEachIndexed
            val plan = planContours(
                contours,
                densityMm = options.satinDensityMm,
                pullMm = options.satinPullCompensationMm
            )
            require(plan.rails.isNotEmpty()) {
                "A fonte não produziu uma faixa Satin segura na letra " +
                    (glyphIndex + 1) + ". Ajuste a altura ou a fonte."
            }
            stitcher.sewGlyph(plan.rails, options.satinUnderlayMode)
            sewnGlyphs++
        }
        require(sewnGlyphs > 0 && points.any { it.command == StitchCommand.STITCH }) {
            "Não foram geradas pontadas válidas."
        }
        val last = points.last()
        points.add(last.copy(command = StitchCommand.END))
        val coords = points.filter { it.command != StitchCommand.END }
        val bounds = EmbroideryBounds(
            minXUnits = coords.minOf { it.xUnits },
            maxXUnits = coords.maxOf { it.xUnits },
            minYUnits = coords.minOf { it.yUnits },
            maxYUnits = coords.maxOf { it.yUnits }
        )
        val design = EmbroideryDesign(
            fileName = "$filePrefix-" +
                text.lowercase(Locale.ROOT).replace(Regex("[^a-z0-9_-]"), "-") +
                "." + format.lowercase(Locale.ROOT),
            format = format,
            label = text,
            points = points,
            bounds = bounds,
            stitchCount = points.count { it.command == StitchCommand.STITCH },
            jumpCount = points.count { it.command == StitchCommand.JUMP },
            colorChanges = 0,
            endFound = true,
            sourceBytes = ByteArray(0),
            threadColors = listOf(options.color),
            sourceYAxisDown = true,
            isModified = true,
            hoopProfile = options.hoopProfile,
            fabricProfile = options.fabricProfile
        )
        EmbroideryStressPolicy.requireGeneratedSafe(design)
        if (options.enforceHoop && options.hoopProfile != null) {
            require(HoopValidator.validate(design, options.hoopProfile).fits) {
                "O bordado ultrapassa o bastidor selecionado."
            }
        }
        design
    }

    internal fun planContours(
        contours: List<List<V>>,
        densityMm: Float,
        pullMm: Float = 0.2f
    ): PlannedGlyph {
        require(densityMm in 0.3f..1.2f)
        val raster = rasterize(contours, densityMm)
        val skeleton = thin(raster)
        val skeletonPixels = skeleton.count { it }
        if (skeletonPixels < 1) return PlannedGlyph(emptyList(), 0, 0)
        val routes = traceEdges(raster, skeleton)
        val pitch = densityMm * 10f
        val claimed = HashMap<Pair<Int, Int>, MutableList<Rail>>()
        // Hairline strokes of an imported script font may be less than
        // 0.3 mm wide in a small hoop. Do not classify adjacent, visibly
        // distinct transverse bars as already-covered rails.
        val tolerance = (pitch * 0.16f).coerceIn(0.35f, 0.75f)
        fun cell(v: V) =
            floor(v.x / (tolerance * 2.4f)).toInt() to
                floor(v.y / (tolerance * 2.4f)).toInt()
        fun sameRail(a: Rail, b: Rail): Boolean =
            length(a.middle, b.middle) <= tolerance &&
                (
                    (length(a.a, b.a) <= tolerance && length(a.b, b.b) <= tolerance) ||
                    (length(a.a, b.b) <= tolerance && length(a.b, b.a) <= tolerance)
                )
        fun seen(rail: Rail): Boolean {
            val (cx, cy) = cell(rail.middle)
            for (dx in -1..1) for (dy in -1..1) {
                if (claimed[cx + dx to cy + dy].orEmpty().any { sameRail(it, rail) }) {
                    return true
                }
            }
            claimed.getOrPut(cell(rail.middle)) { mutableListOf() }.add(rail)
            return false
        }
        val result = mutableListOf<List<Rail>>()
        var duplicates = 0
        // Planejamento determinístico por continuidade do traço e não por
        // distância isolada: termina a ramificação corrente antes de trocar
        // para uma área distante que exigiria retorno visual.
        val orderedRoutes = orderSkeletonRoutes(routes, raster.step)
        orderedRoutes.forEach { route ->
            val interpolated = resample(route, pitch)
            var batch = mutableListOf<Rail>()
            fun endBatch() {
                if (batch.isNotEmpty()) result += batch
                batch = mutableListOf()
            }
            interpolated.forEachIndexed { i, c ->
                val prev = interpolated[(i - 1).coerceAtLeast(0)]
                val next = interpolated[(i + 1).coerceAtMost(interpolated.lastIndex)]
                val tangent = normalized(V(next.x - prev.x, next.y - prev.y))
                if (tangent == null) return@forEachIndexed
                val row = crossSection(raster, c, V(-tangent.y, tangent.x), pullMm * 10f)
                if (row == null || length(row.a, row.b) < 1.5f) {
                    endBatch()
                } else if (seen(row)) {
                    duplicates++
                    endBatch()
                } else {
                    batch.add(row)
                }
            }
            endBatch()
        }
        // Disconnected dot components of imported fonts can collapse to a
        // single skeleton pixel. Such a pixel creates only one Satin bar and
        // turns the dot into a thin dash. Refill only these small, *detached*
        // upper accents, keeping all other glyph paths and needle routing.
        val restoredDots = buildDetachedDotRails(raster, densityMm, pullMm)
        if (restoredDots.isNotEmpty()) {
            result.removeAll { path ->
                val middle = path.firstOrNull()?.middle
                middle != null && restoredDots.any { dot ->
                    middle.x in dot.left..dot.right &&
                        middle.y in dot.top..dot.bottom
                }
            }
            // Um pingo superior é finalizado ANTES de descer a haste:
            // nunca voltar para o topo depois de concluir a letra.
            result.addAll(0, restoredDots.map { it.rails })
        }
        return PlannedGlyph(result, orderedRoutes.sumOf { it.size }, duplicates)
    }

    internal fun orderSkeletonRoutes(
        routes: List<List<V>>,
        gridStep: Float
    ): List<List<V>> {
        val pending = routes.filter { it.size >= 2 }.toMutableList()
        if (pending.isEmpty()) return emptyList()
        val ordered = mutableListOf<List<V>>()
        var previousEnd: V? = null
        var previousDirection: V? = null
        val joinTolerance = max(2f, gridStep * 1.8f)

        while (pending.isNotEmpty()) {
            var bestIndex = 0
            var bestReversed = false
            var bestScore = Float.POSITIVE_INFINITY
            for (i in pending.indices) {
                val segment = pending[i]
                for (reversed in listOf(false, true)) {
                    val entry = if (reversed) segment.last() else segment.first()
                    val exit = if (reversed) segment.first() else segment.last()
                    val score = if (previousEnd == null) {
                        // Começar pela extremidade esquerda mais baixa.
                        entry.x * 3f - entry.y * 0.08f
                    } else {
                        val gap = length(previousEnd, entry)
                        if (gap <= joinTolerance) {
                            val next = if (reversed) segment[segment.lastIndex - 1]
                                else segment[1]
                            val direction = normalized(V(next.x - entry.x, next.y - entry.y))
                            val alignment = if (previousDirection != null &&
                                direction != null) {
                                (previousDirection.x * direction.x +
                                    previousDirection.y * direction.y).coerceIn(-1f, 1f)
                            } else 0f
                            // Preferir seguir reto no mesmo ramo do esqueleto.
                            gap * 2f + (1f - alignment) * joinTolerance * 3f
                        } else {
                            // Um salto separa ramos desconectados. Visitar
                            // primeiro o que resta à esquerda, sem costurar
                            // linhas de ligação ou regressos longos.
                            val back = max(0f, previousEnd.x - entry.x)
                            10000f + entry.x * 2f + gap * 0.5f + back * 3f
                        }
                    }
                    if (score < bestScore) {
                        bestScore = score
                        bestIndex = i
                        bestReversed = reversed
                    }
                }
            }
            val selected = pending.removeAt(bestIndex)
            val oriented = if (bestReversed) selected.asReversed() else selected
            ordered += oriented
            previousEnd = oriented.last()
            val last = oriented[oriented.lastIndex - 1]
            previousDirection = normalized(V(previousEnd.x - last.x, previousEnd.y - last.y))
        }
        return ordered
    }

    private data class DotRails(
        val left: Float,
        val top: Float,
        val right: Float,
        val bottom: Float,
        val rails: List<Rail>
    )

    private data class FilledIsland(
        val minX: Int,
        val minY: Int,
        val maxX: Int,
        val maxY: Int,
        val pixelCount: Int
    )

    /**
     * Restore tiny, detached upper marks (e.g. the dot above i or j) using
     * real horizontal Satin rails sampled from their existing font outlines.
     * It does not draw a synthetic circle or interfere with the main glyph.
     */
    private fun buildDetachedDotRails(
        raster: Raster,
        densityMm: Float,
        pullMm: Float
    ): List<DotRails> {
        val visited = BooleanArray(raster.mask.size)
        val islands = mutableListOf<FilledIsland>()
        for (seed in raster.mask.indices) {
            if (!raster.mask[seed] || visited[seed]) continue
            val queue = java.util.ArrayDeque<Int>()
            queue.add(seed)
            visited[seed] = true
            var count = 0
            var minX = raster.width
            var minY = raster.height
            var maxX = 0
            var maxY = 0
            while (!queue.isEmpty()) {
                val pixel = queue.removeFirst()
                val x = pixel % raster.width
                val y = pixel / raster.width
                count++
                minX = minOf(minX, x)
                maxX = maxOf(maxX, x)
                minY = minOf(minY, y)
                maxY = maxOf(maxY, y)
                for (dy in -1..1) for (dx in -1..1) {
                    if (dx == 0 && dy == 0) continue
                    val nx = x + dx
                    val ny = y + dy
                    if (nx !in 0 until raster.width ||
                        ny !in 0 until raster.height) continue
                    val next = raster.index(nx, ny)
                    if (raster.mask[next] && !visited[next]) {
                        visited[next] = true
                        queue.add(next)
                    }
                }
            }
            islands += FilledIsland(minX, minY, maxX, maxY, count)
        }
        val body = islands.maxByOrNull { it.pixelCount } ?: return emptyList()
        val bodyHeight = (body.maxY - body.minY + 1) * raster.step
        if (bodyHeight < 10f) return emptyList()
        val rowPitch = max(1, (densityMm * 10f / raster.step).roundToInt())
        return islands.asSequence()
            .filter { island ->
                if (island === body || island.maxY >= body.minY) return@filter false
                val w = (island.maxX - island.minX + 1) * raster.step
                val h = (island.maxY - island.minY + 1) * raster.step
                val ratio = w / h
                w <= minOf(55f, bodyHeight * 0.48f) &&
                    h <= minOf(55f, bodyHeight * 0.48f) &&
                    ratio in 0.45f..2.2f &&
                    island.pixelCount * 4 < body.pixelCount
            }
            .sortedBy { it.minX }
            .mapNotNull { island ->
                val filledRows = (island.minY..island.maxY).filter { y ->
                    (island.minX..island.maxX).any { x -> raster.inside(x, y) }
                }
                if (filledRows.isEmpty()) return@mapNotNull null
                val selected = filledRows.filterIndexed { index, _ ->
                    index % rowPitch == 0
                }.toMutableSet()
                if (selected.size < 3 && filledRows.size >= 3) {
                    selected += filledRows.first()
                    selected += filledRows[filledRows.size / 2]
                    selected += filledRows.last()
                }
                val pullUnits = pullMm * 10f
                val rails = selected.sorted().mapNotNull { y ->
                    val occupied = (island.minX..island.maxX)
                        .filter { x -> raster.inside(x, y) }
                    if (occupied.isEmpty()) return@mapNotNull null
                    // Every bar follows the original mask width at this row.
                    val left = raster.left + occupied.first() * raster.step
                    val right = raster.left + occupied.last() * raster.step
                    val atY = raster.top + y * raster.step
                    Rail(
                        V(left - raster.step * 0.45f - pullUnits, atY),
                        V(right + raster.step * 0.45f + pullUnits, atY)
                    )
                }
                if (rails.isEmpty()) return@mapNotNull null
                DotRails(
                    raster.left + (island.minX - 1) * raster.step,
                    raster.top + (island.minY - 1) * raster.step,
                    raster.left + (island.maxX + 1) * raster.step,
                    raster.top + (island.maxY + 1) * raster.step,
                    rails
                )
            }
            .toList()
    }

    private fun rasterize(contours: List<List<V>>, densityMm: Float): Raster {
        val points = contours.flatten()
        require(points.isNotEmpty()) { "Fonte sem contorno." }
        val minX = points.minOf { it.x }
        val maxX = points.maxOf { it.x }
        val minY = points.minOf { it.y }
        val maxY = points.maxOf { it.y }
        // No bastidor pequeno os detalhes cursivos podem ter menos de
        // 0,25 mm: evitar que a amostragem grosseira quebre o contorno.
        var step = max(0.75f, densityMm * 10f * 0.26f)
        var width = ceil((maxX - minX) / step).toInt() + 5
        var height = ceil((maxY - minY) / step).toInt() + 5
        while (width.toLong() * height.toLong() > 350_000) {
            step *= 1.2f
            width = ceil((maxX - minX) / step).toInt() + 5
            height = ceil((maxY - minY) / step).toInt() + 5
        }
        val left = minX - step * 2
        val top = minY - step * 2
        val mask = BooleanArray(width * height)
        // Conservative subpixel scan conversion: sample the centre and two
        // nearby Y positions within each pixel row. A very narrow cursive
        // stroke must not disappear just because it misses a grid centre.
        // Keep the TrueType non-zero winding rule and the original contours;
        // no closing/dilation is applied to large areas or letter counters.
        fun fillRow(pixelY: Int, sampleY: Float) {
            val intersections = mutableListOf<Pair<Float, Int>>()
            contours.forEach { polygon ->
                if (polygon.size < 3) return@forEach
                polygon.indices.forEach { i ->
                    val a = polygon[i]
                    val b = polygon[(i + 1) % polygon.size]
                    if ((a.y <= sampleY && b.y > sampleY) ||
                        (b.y <= sampleY && a.y > sampleY)) {
                        val x = a.x +
                            (sampleY - a.y) * (b.x - a.x) / (b.y - a.y)
                        intersections += x to (if (b.y > a.y) 1 else -1)
                    }
                }
            }
            intersections.sortBy { it.first }
            var winding = 0
            for (i in 0 until intersections.lastIndex) {
                winding += intersections[i].second
                if (winding == 0) continue
                val leftX = intersections[i].first
                val rightX = intersections[i + 1].first
                val from = max(1, ceil((leftX - left) / step).toInt())
                val to = minOf(width - 2, floor((rightX - left) / step).toInt())
                if (from <= to) {
                    for (x in from..to) mask[pixelY * width + x] = true
                } else if (rightX > leftX) {
                    // Preserve a genuine filled interval thinner than one
                    // raster cell. Crucial at the tips of M/a/r/i.
                    val nearest = (((leftX + rightX) * 0.5f - left) / step)
                        .roundToInt().coerceIn(1, width - 2)
                    mask[pixelY * width + nearest] = true
                }
            }
        }
        for (y in 1 until height - 1) {
            val rowY = top + y * step
            fillRow(y, rowY)
            fillRow(y, rowY - step * 0.30f)
            fillRow(y, rowY + step * 0.30f)
        }
        return Raster(width, height, step, left, top, mask)
    }

    // Zhang-Suen skeletonization: a mask pixel may be deleted only if the
    // local 8-neighborhood remains connected. Boundary crossings are unique.
    private fun thin(raster: Raster): BooleanArray {
        val pixels = raster.mask.copyOf()
        val w = raster.width
        val h = raster.height
        fun on(x: Int, y: Int) = pixels[y * w + x]
        var changed = true
        var pass = 0
        while (changed && pass < 220) {
            changed = false
            for (phase in 0..1) {
                val erase = mutableListOf<Int>()
                for (y in 1 until h - 1) for (x in 1 until w - 1) {
                    if (!on(x, y)) continue
                    val n = booleanArrayOf(
                        on(x, y-1), on(x+1, y-1), on(x+1, y),
                        on(x+1, y+1), on(x, y+1), on(x-1, y+1),
                        on(x-1, y), on(x-1, y-1)
                    )
                    val count = n.count { it }
                    if (count !in 2..6) continue
                    val transitions = n.indices.count { !n[it] && n[(it+1)%8] }
                    if (transitions != 1) continue
                    val p2 = n[0]; val p4 = n[2]; val p6 = n[4]; val p8 = n[6]
                    val condition = if (phase == 0) {
                        !(p2 && p4 && p6) && !(p4 && p6 && p8)
                    } else {
                        !(p2 && p4 && p8) && !(p2 && p6 && p8)
                    }
                    if (condition) erase += y * w + x
                }
                erase.forEach { pixels[it] = false }
                if (erase.isNotEmpty()) changed = true
            }
            pass++
        }
        return pixels
    }

    private fun traceEdges(raster: Raster, skeleton: BooleanArray): List<List<V>> {
        val w = raster.width
        val h = raster.height
        fun neighbors(i: Int): List<Int> {
            val x = i % w; val y = i / w
            val out = mutableListOf<Int>()
            for (dy in -1..1) for (dx in -1..1) {
                if (dx == 0 && dy == 0) continue
                val nx = x + dx; val ny = y + dy
                if (nx !in 0 until w || ny !in 0 until h) continue
                val neighbor = ny * w + nx
                if (!skeleton[neighbor]) continue
                // 4-connected orthogonal alternatives remove diagonal
                // shortcuts that generate loops at 90-degree bends.
                if (dx != 0 && dy != 0 &&
                    (skeleton[y * w + nx] || skeleton[ny * w + x])) continue
                out += neighbor
            }
            return out
        }
        val nodes = skeleton.indices.filter { skeleton[it] }
        val used = HashSet<Edge>()
        val paths = mutableListOf<List<V>>()
        fun walk(source: Int, first: Int) {
            var previous = source
            var current = first
            val track = mutableListOf(source, first)
            used.add(Edge.of(source, first))
            while (true) {
                val available = neighbors(current)
                    .filter { it != previous && Edge.of(it, current) !in used }
                if (available.size != 1) break
                val next = available[0]
                used.add(Edge.of(current, next))
                previous = current
                current = next
                track.add(current)
                if (current == source) break
            }
            if (track.size >= 2) paths += track.map(raster::point)
        }
        // Endpoints / branches first; loops and remaining edges second.
        val ordered = nodes.sortedWith(compareBy<Int> {
            if (neighbors(it).size == 2) 1 else 0
        }.thenBy { it % w })
        ordered.forEach { node ->
            neighbors(node).forEach { next ->
                if (Edge.of(node, next) !in used) walk(node, next)
            }
        }
        // Pontos e ilhas pequenos (como o pingo do i) afinam ate
        // um unico pixel e nao possuem arestas. Eles tambem precisam
        // gerar preenchimento, sem serem descartados.
        nodes.filter { neighbors(it).isEmpty() }.forEach { lone ->
            val p = raster.point(lone)
            val half = raster.step * 0.60f
            paths += listOf(
                V(p.x, p.y - half),
                p,
                V(p.x, p.y + half)
            )
        }
        return paths
    }

    private fun resample(path: List<V>, pitch: Float): List<V> {
        if (path.size < 2) return path
        val lengths = path.zipWithNext().map { (a,b) -> length(a,b) }
        val total = lengths.sum()
        if (total < pitch * 0.55f) return path
        val count = max(2, (total / pitch).roundToInt() + 1)
        val samples = mutableListOf<V>()
        var seg = 0
        var before = 0f
        for (i in 0 until count) {
            val d = total * i / (count - 1)
            while (seg < lengths.lastIndex && before + lengths[seg] < d) {
                before += lengths[seg]
                seg++
            }
            val fraction = if (lengths[seg] <= 0f) 0f else
                ((d - before) / lengths[seg]).coerceIn(0f,1f)
            val a = path[seg]
            val b = path[seg+1]
            samples += V(
                a.x + (b.x - a.x) * fraction,
                a.y + (b.y - a.y) * fraction
            )
        }
        return samples
    }

    private fun crossSection(
        mask: Raster, center: V, normal: V, pullUnits: Float
    ): Rail? {
        val sampling = minOf(0.85f, mask.step / 2f)
        fun insideAt(x: Float, y: Float): Boolean {
            val xi = ((x - mask.left) / mask.step).roundToInt()
            val yi = ((y - mask.top) / mask.step).roundToInt()
            return mask.inside(xi, yi)
        }
        val effectiveCenter = if (insideAt(center.x, center.y)) {
            center
        } else {
            // Chord interpolation at a sharp bend can fall just outside a
            // narrow glyph. Snap at most one mask pixel, never bridge holes.
            val cx = ((center.x - mask.left) / mask.step).roundToInt()
            val cy = ((center.y - mask.top) / mask.step).roundToInt()
            val nearest = (-1..1).flatMap { dy ->
                (-1..1).map { dx -> cx + dx to cy + dy }
            }.filter { (x, y) -> mask.inside(x, y) }
                .minByOrNull { (x, y) ->
                    val px = mask.left + x * mask.step
                    val py = mask.top + y * mask.step
                    length(center, V(px, py))
                } ?: return null
            V(mask.left + nearest.first * mask.step,
                mask.top + nearest.second * mask.step)
        }
        val maxExtent = 35f // 7 mm full satin width limit
        fun edge(sign: Float): Float {
            var d = 0f
            while (d <= maxExtent &&
                insideAt(
                    effectiveCenter.x + normal.x * d * sign,
                    effectiveCenter.y + normal.y * d * sign
                )) d += sampling
            // A última célula ocupada representa uma área finita, não
            // um ponto sem largura. Metade da célula evita perder a
            // cobertura em hastes cursivas de um único pixel.
            return (d - sampling).coerceAtLeast(mask.step * 0.5f)
        }
        val a = edge(-1f)
        val b = edge(1f)
        val originalWidth = a + b
        if (originalWidth < mask.step * 0.45f) return null
        // Avoid inflating 0.1 mm hairlines by a full pull-compensation
        // amount on each side. Preserve the user's configured value for
        // normal-width Satin strokes.
        val safePull = minOf(pullUnits, max(0.4f, originalWidth * 0.5f))
        return Rail(
            V(effectiveCenter.x - normal.x * (a + safePull),
                effectiveCenter.y - normal.y * (a + safePull)),
            V(effectiveCenter.x + normal.x * (b + safePull),
                effectiveCenter.y + normal.y * (b + safePull))
        )
    }

    internal fun stitchPlannedGlyphForTest(
        planned: PlannedGlyph,
        underlay: SatinUnderlayMode = SatinUnderlayMode.NONE
    ): List<EmbroideryPoint> {
        val points = mutableListOf<EmbroideryPoint>()
        Stitcher(points).sewGlyph(planned.rails, underlay)
        return points
    }

    private class Stitcher(val points: MutableList<EmbroideryPoint>) {
        private var needle: V? = null
        private fun command(p: V, cmd: StitchCommand) {
            val x = p.x.roundToInt()
            val y = p.y.roundToInt()
            val last = points.lastOrNull()
            if (last != null &&
                last.xUnits == x && last.yUnits == y &&
                last.command == cmd) return
            require(points.size < EmbroideryStressPolicy.MAX_GENERATED_COMMANDS) {
                "A fonte gerou pontos demais; tente menor altura ou outro estilo."
            }
            points += EmbroideryPoint(x, y, cmd, 0)
            needle = p
        }
        private fun jump(p: V) {
            val start = needle
            if (start != null && length(start, p) < 0.5f) return
            command(p, StitchCommand.JUMP)
        }
        private fun sew(p: V) {
            val start = needle
            if (start == null) { jump(p); return }
            val distance = length(start, p)
            if (distance < 0.45f) return
            val chunks = max(1, ceil(distance / 70f).toInt())
            for (k in 1..chunks) {
                val t = k.toFloat() / chunks
                command(V(start.x+(p.x-start.x)*t, start.y+(p.y-start.y)*t),
                    StitchCommand.STITCH)
            }
        }
        fun sewGlyph(paths: List<List<Rail>>, underlay: SatinUnderlayMode) {
            var anchored = false
            paths.forEach { rows ->
                if (rows.isEmpty()) return@forEach
                // Orientação já calculada pelo planejador de traços.
                // Não inverter um ramo novamente por proximidade física.
                val begin = rows.first().middle
                val doUnderlay = underlay != SatinUnderlayMode.NONE && rows.size >= 6
                if (doUnderlay) {
                    jump(begin)
                    // One center run, then satin in reverse without
                    // retracing the center back to the start.
                    for (index in rows.indices step 5) sew(rows[index].middle)
                    sew(rows.last().middle)
                }
                val cover = if (doUnderlay) rows.asReversed() else rows
                val entry = cover.first().a
                val lastPos = needle
                if (lastPos == null || length(lastPos, entry) > 4f) jump(entry)
                else sew(entry)
                if (!anchored) {
                    // One short tie-in for this glyph, not every medial branch.
                    val r = cover.first()
                    val t = V(r.a.x + (r.b.x-r.a.x)*0.08f,
                        r.a.y + (r.b.y-r.a.y)*0.08f)
                    sew(t)
                    sew(r.a)
                    anchored = true
                }
                cover.forEach { rail ->
                    sew(rail.a)
                    sew(rail.b)
                }
            }
            // There are deliberately NO per-path tie-off round trips.
            // The machine-facing finishing policy handles last tie/trim.
        }
    }

    private fun length(a: V, b: V) =
        hypot((b.x-a.x).toDouble(), (b.y-a.y).toDouble()).toFloat()
    private fun normalized(v: V): V? {
        val n = hypot(v.x.toDouble(), v.y.toDouble()).toFloat()
        return if (n < 0.0001f) null else V(v.x/n, v.y/n)
    }
}
